In [16]:
#importing required libraries
import numpy as np
import pandas as pd

In [17]:
#importing dataset
data = pd.read_csv('E:\\Top mentor files\\Batch 83 Day 24\\Social_Network_Ads.csv')
ads = data.copy()
ads.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  11021175    Male   42           121315          0
1  17782313    Male   53            67214          0
2  14603818  Female   59           111005          0
3  18188198  Female   39            53414          0
4  19357305    Male   39           114285          0

In [18]:
#checking shape
print(f'No. of Rows {ads.shape[0]}')
print(f'No. of Columns {ads.shape[1]}')

No. of Rows 400
No. of Columns 5


In [65]:
#Getting statistical insights from dataset
ads.describe()

Gender           Age  EstimatedSalary   Purchased
count  400.000000  4.000000e+02     4.000000e+02  400.000000
mean     0.510000  7.771561e-18    -2.333689e-15    0.357500
std      0.500526  1.001252e+00     1.001252e+00    0.479864
min      0.000000 -2.050359e+00    -2.145247e+00    0.000000
25%      0.000000 -7.578037e-01    -7.565084e-01    0.000000
50%      1.000000  1.592788e-01     1.260285e-01    0.000000
75%      1.000000  9.337507e-01     8.335702e-01    1.000000
max      1.000000  1.451834e+00     1.489790e+00    1.000000

In [66]:
#Getting infomation of the dataset
ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Gender           400 non-null    int64  
 1   Age              400 non-null    float64
 2   EstimatedSalary  400 non-null    float64
 3   Purchased        400 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 12.6 KB


User Id seems to be of little use

In [19]:
#Dropping user id column
ads = ads.drop(['User ID'], axis=1)

In [20]:
#label encoding gender column
ads['Gender'] = ads['Gender'].map({'Male':0, 'Female':1})
ads.head()

Gender  Age  EstimatedSalary  Purchased
0       0   42           121315          0
1       0   53            67214          0
2       1   59           111005          0
3       1   39            53414          0
4       0   39           114285          0

In [37]:
#Scaling age and estimated salary column
from sklearn.preprocessing import StandardScaler
scaled = StandardScaler()

In [44]:
#Changing age and estimated salary column to scaled values 
ads['Age'] = scaled.fit_transform(ads[['Age']])
ads['EstimatedSalary'] = scaled.fit_transform(ads[['EstimatedSalary']])

In [45]:
#Checking head to see if dataset looks fine
ads.head()

Gender       Age  EstimatedSalary  Purchased
0       0  0.314814         0.794561          0
1       0  1.056375        -1.167293          0
2       1  1.398256         0.499490          0
3       1  0.078570        -1.930789          0
4       0  0.078570         0.596236          0

Dataset looks fine now

In [46]:
#Splitting into independent and dependent variable
X = ads.iloc[:,:-1]
y = ads.iloc[:,-1]

In [47]:
#Splitting into training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(320, 3)
(80, 3)
(320,)
(80,)


In [48]:
#Creating classification models

#Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

#KNN Regressor
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

#Decision Tree
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()

#Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

from sklearn.svm import SVC
svc = SVC()

models_list = [lr, knn, dt, rf, svc]

In [52]:
#Importing libraries to check score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [64]:
#for loop to iterate through models list, training, predicting, checking accuracy of each model
for model in models_list:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    score = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    print(f'\nThe score for {model} model is {score*100}')
    print(f'The confusion matrix for {model} model is \n{cm}')
    print(f'Correctly predicted {cm[0,0]+cm[1,1]} values out of {cm[0,0] + cm[0,1] + cm[1,0] + cm[1,1]} values')


The score for LogisticRegression() model is 70.0
The confusion matrix for LogisticRegression() model is 
[[56  0]
 [24  0]]
Correctly predicted 56 values out of 80 values

The score for KNeighborsClassifier() model is 56.25
The confusion matrix for KNeighborsClassifier() model is 
[[43 13]
 [22  2]]
Correctly predicted 45 values out of 80 values

The score for DecisionTreeRegressor() model is 55.00000000000001
The confusion matrix for DecisionTreeRegressor() model is 
[[37 19]
 [17  7]]
Correctly predicted 44 values out of 80 values

The score for RandomForestClassifier() model is 62.5
The confusion matrix for RandomForestClassifier() model is 
[[43 13]
 [17  7]]
Correctly predicted 50 values out of 80 values

The score for SVC() model is 70.0
The confusion matrix for SVC() model is 
[[56  0]
 [24  0]]
Correctly predicted 56 values out of 80 values


Conclusion

Logistic Regression and Support vector regressor works best on this dataset